### model
model_name_or_path: /models//models/Meta-Llama-3.1-8B-Instruct-SFT

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: culturebank_data_twitter_reddit_prune_0.7
template: llama3
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/home/frx/cultural_llm/lora_weights/llama3.1-DPO-ablation-reward/0.7
logging_steps: 10
save_steps: 200
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 2
gradient_accumulation_steps: 4
learning_rate: 5.0e-6
num_train_epochs: 20
lr_scheduler_type: cosine
warmup_ratio: 0.1
lora_rank: 16
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 500

#Finetune args
pref_ftx: 1.0
