### model
model_name_or_path: /data/home/frx/cultural_llm/models/Qwen2.5-Instruct-7B-1-20

### method
stage: dpo
do_train: true
finetuning_type: lora
lora_target: all
pref_beta: 0.1
pref_loss: sigmoid  # choices: [sigmoid (dpo), orpo, simpo]

### dataset
dataset: /data/home/frx/cultural_llm/lora_weights/llama3.1-DPO-ablation-reward/0.7
template: qwen
cutoff_len: 2048
max_samples: 1000
overwrite_cache: true
preprocessing_num_workers: 16

### output
output_dir: /data/home/frx/cultural_llm/lora_weights/qwen2.5-dpo
logging_steps: 10
save_steps: 100
plot_loss: true
overwrite_output_dir: true

### train
per_device_train_batch_size: 1
gradient_accumulation_steps: 8
learning_rate: 1.0e-6
num_train_epochs: 20
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
val_size: 0.05
per_device_eval_batch_size: 1
eval_strategy: steps
eval_steps: 50


#Finetune args
pref_ftx: 0.5
lora_rank: 16
